---
config:
  layout: grid
  flowchart:
    nodeSpacing: 100
---
graph TD
	%% Nodes
	ScientificKnowledge("Conhecimento Científico")

    FormalSciences("Ciências Formais")
	NaturalSciences("Ciências Naturais")
	SocialSciences("Ciências Sociais")

	Logic("Lógica")
	Mathematics("Matemática")
	ComputerScience("Ciência da Computação")

	TheoreticalComputerScience("Ciência da Computação<br>Teórica")
	AppliedComputerScience("Ciência da Computação<br>Aplicada")

	ComputerScience_TheoreticalComputerScience_InformationTheory("Teoria da Informação")
	ComputerScience_TheoreticalComputerScience_ComputationTheory("Teoria da Computação")

	%%////////////////////////////////////////////////////////////////////////////////%%

	ScientificKnowledge --> FormalSciences
	ScientificKnowledge --> NaturalSciences
	ScientificKnowledge --> SocialSciences

	FormalSciences --> Logic
	FormalSciences --> Mathematics
	FormalSciences --> ComputerScience

	ComputerScience --> TheoreticalComputerScience
	ComputerScience --> AppliedComputerScience

	TheoreticalComputerScience --> ComputerScience_TheoreticalComputerScience_InformationTheory
	TheoreticalComputerScience --> ComputerScience_TheoreticalComputerScience_ComputationTheory
